### ISSUE TITLE
Update readme adding .Net 3.5 requirements

### ISSUE THREAD

**Issue by miyconst** [Smorgasbord-Development/DatabaseEditor#11]
The database editor app requires .Net 3.5, which is not installed on Windows 10 machines by default, this causes an error during startup.

```
System.Exception: ScErrWeaverFailedResolveReference (SCERR2147): The weaver failed to resolve a reference to an assembly. Referenced assembly: System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089. Probable referrer: Starcounter.Extensions.dll (in C:\Program Files\Starcounter\LibrariesWithDatabaseClasses). Version: 2.3.0.6318. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2147.
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in C:\TeamCity\BuildAgent\work\sc-4875\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in C:\TeamCity\BuildAgent\work\sc-4875\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__2(CommandTask task) in C:\TeamCity\BuildAgent\work\sc-4875\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\BuildAgent\work\sc-4875\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\BuildAgent\work\sc-4875\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\BuildAgent\work\sc-4875\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-4875\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2147
```

**Comment by andwah** [comment]
README updated

**Comment by warpech** [comment]
I am getting the same error in another app. How do you know from this stack trace that this is because of missing .Net 3.5? 

In my case, installing .Net 3.5 did not help.

**Comment by miyconst** [comment]
@warpech, there is no way to know this from the stack trace, I just know the app, and know what it requires.

Weaver will fail with same stack trace if any other .Net version is missing, but required. Same thing if an app referenced a missing assembly.

**Comment by warpech** [comment]
Thanks!

Turned out that in my case .Net 2.0 was expected. I needed to upgrade my NuGet dependencies to current versions that work with 4.5.2.
