### ISSUE TITLE
Question : Is this Repo SC 2.3 compatible? 

### ISSUE THREAD

**Issue by atifwaqar** [Smorgasbord-Development/DatabaseEditor#8]
##### Starcounter version 
2.3.0.5828

### Screenshot
![image](https://cloud.githubusercontent.com/assets/4388707/23822342/c4201fc6-064b-11e7-99f6-4448d6052908.png)

**Comment by andwah** [comment]
Strange. it should be,  do you use the "latest" v1.0.17.0 of the DatabaseEditor?

**Comment by andwah** [comment]
if not try downloading it from Starcounter Administrator -> App Warehouse

**Comment by atifwaqar** [comment]
Yes I am using the latest version, and I tried downloading from App Warehouse as well, it's showing the same error. Also on app warehouse I have to uncheck `Show Compatible` to install this app. and I see 2.2 compatible version: 
![image](https://cloud.githubusercontent.com/assets/4388707/23824139/6053328c-0671-11e7-9158-e8f2675c6899.png)

**Comment by atifwaqar** [comment]
Oops my bad, I am on version `1.0.16`. How to get `1.0.17.0`?

**Comment by andwah** [comment]
Strange that it does not show up in the list.. i will investigate ..

**Comment by andwah** [comment]
Resolved, try refreshing the app warehouse page and you will now see the latest version.

**Comment by atifwaqar** [comment]
When I start the app it shows following exception:
```
System.Exception: ScErrWeaverFailedResolveReference (SCERR2147): The weaver failed to resolve a reference to an assembly. Referenced assembly: System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089. Probable referrer: Starcounter.Extensions.dll (in C:\Program Files\Starcounter\LibrariesWithDatabaseClasses). Version: 2.3.0.5828. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2147.
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__2(CommandTask task) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2147
```

Do you think is this because of a different SC version? In Warehouse I see `Version 2.3.0.5489` under this app.

**Comment by andwah** [comment]
Not sure what's going on.. Maybe i need to recompile the app with sc 2.3.0.5828.

is it a new Starcounter installation?..

**Comment by atifwaqar** [comment]
Yes it is a new Starcounter installation.

**Comment by andwah** [comment]
Check this issue https://github.com/Starcounter/Starcounter/issues/3744  

Maybe you are missing .NET Framework 3.5 ?

**Comment by atifwaqar** [comment]
My server was missing .NET 3.5.
Thanks @andwah.
